### ISSUE TITLE
meeseeks.cow file

### ISSUE THREAD

**Issue by EliasJorgensen** [garymh/dotfiles#2]
Where did you get this file?
I have been scouring the internet for this, but the closest i have come is your dotfiles!
Any help is appreciated!

**Comment by garymh** [comment]
I actually created it with https://github.com/rossy/img2xterm - it includes a binary called 'img2cow' that lets you convert PNGs to cow files! Unless you mean the .PNG source... afraid I don't remember that. I believe I just did a google image search for 'meeseeks'
